name: Publish a Pre-Release

on:
  release:
    types: [prereleased]

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
    - name: Pull down the Nuget Package
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: SemanticConsole.${{ github.ref_name }}.nupkg
        target: SemanticConsole.${{ github.ref_name }}.nupkg

    - name: Publish the Package
      run: dotnet nuget push "SemanticConsole.${{ github.ref_name }}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/yozepi/index.json"