name: Release

on:
  push:
    branches:
      - 'main'
      - 'rc'
      - 'beta'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Environment
        id: dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Run Unit Tests
        id: unittest
        run: dotnet test ./ExampleUnitTests/ExampleUnitTests.csproj --configuration=Release

      - name: Update and Pack the Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          branches: "['main', {name: 'rc', prerelease: true}, {name: 'beta', prerelease: true}]"
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Artifacts
        id: artifacts
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: artifacts
          path: ./artifacts/**/*.*
          retention-days: 0

      - name: Display Release Info
        run: |
          echo Last Release: ${{ steps.semantic.outputs.last_release_version }}
          echo This Release: ${{ steps.semantic.outputs.new_release_version }}
