name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'rc'
      - 'beta'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Environment
        id: dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Run Unit Tests
        id: unittest
        run: dotnet test ./ExampleUnitTests/ExampleUnitTests.csproj --configuration=Release

      - name: Create the Release Tag
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          branches: "['main', {name: 'rc', prerelease: true}, {name: 'beta', prerelease: true}]"
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GIT_CREDENTIALS: ${{ secrets.CI_ACCESS_TOKEN }}

      - name: Build The NuGet Package
        id: nugetPackage
        if: steps.semantic.outputs.new_release_published == 'true'
        run: dotnet pack -o ./artifacts/nuget --configuration=Release -p:Version=${{ steps.semantic.outputs.new_release_version }}
    
      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          tag_name: ${{ steps.semantic.outputs.new_release_version }}
          body: ${{ steps.semantic.outputs.new_release_notes }}
          files: ./artifacts/**/*.*
          prerelease: ${{ github.ref_name != 'main' }}
          
      - name: Display Release Info
        run: |
          echo Last Release: ${{ steps.semantic.outputs.last_release_version }}
          echo This Release: ${{ steps.semantic.outputs.new_release_version }}
