name: Release

on:
  push:
    branches:
      - 'main'
      - 'next'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Semantic-Release dependencies
        run: npm install

      - name: Semantic-Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          branches: "['main', 'next']"
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo New Release? ${{ steps.semantic.outputs.new_release_version }}
          echo Last Release: ${{ steps.semantic.outputs.last_release_version }}
          echo This Release: ${{ steps.semantic.outputs.new_release_version }}
